name: continuous-integration

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  pr-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4']

    name: PHP ${{ matrix.php-versions }}
    steps:
    - uses: actions/checkout@master

    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug

    - name: Load dependencies from cache
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-php${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php${{ matrix.php-versions }}-composer-

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies (<=PHP 7.3)
      if: matrix.php-versions != '7.4'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install dependencies (PHP 7.4)
      if: matrix.php-versions == '7.4'
      run: composer install --prefer-dist --no-progress --no-suggest --ignore-platform-reqs

    - name: PHP Coding Standards
      if: matrix.php-versions == '7.2'
      run: composer run-script cs

    - name: PHP Static Analysis (PHPStan)
      if: matrix.php-versions == '7.2'
      run: composer run-script phpstan

    - name: PHP Unit Tests with coverage
      if: matrix.php-versions == '7.2'
      run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

    - name: PHP Unit Tests
      if: matrix.php-versions != '7.2'
      run: vendor/bin/phpunit

    - name: Send to coveralls
      if: matrix.php-versions == '7.2'
      run: php vendor/bin/php-coveralls -v
      env:
        COVERALLS_RUN_LOCALLY: 1
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
